version: '3'

services:
  qgMySQLServer:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: deimantas
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: beertest
    volumes:
    - ./src/db:/docker-entrypoint-initdb.d
    ports:
    - "3306:3306"